-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2025-05-08 09:44:47 IST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



DROP TABLE c##hr.categories CASCADE CONSTRAINTS;

DROP TABLE c##hr.customers CASCADE CONSTRAINTS;

DROP TABLE c##hr.inventory CASCADE CONSTRAINTS;

DROP TABLE c##hr.order_items CASCADE CONSTRAINTS;

DROP TABLE c##hr.orders CASCADE CONSTRAINTS;

DROP TABLE c##hr.products CASCADE CONSTRAINTS;

DROP TABLE c##hr.suppliers CASCADE CONSTRAINTS;

CREATE USER c##hr IDENTIFIED BY account

unlock;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE c##hr.categories (
    categoryid   NUMBER NOT NULL,
    categoryname VARCHAR2(100 BYTE) NOT NULL
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.categories
    ADD CONSTRAINT categories_pk
        PRIMARY KEY ( categoryid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

CREATE TABLE c##hr.customers (
    customerid   NUMBER NOT NULL,
    customername VARCHAR2(100 BYTE),
    email        VARCHAR2(100 BYTE),
    address      VARCHAR2(255 BYTE),
    phone        VARCHAR2(15 BYTE)
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.customers
    ADD CONSTRAINT customers_pk
        PRIMARY KEY ( customerid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

CREATE TABLE c##hr.inventory (
    inventoryid     NUMBER NOT NULL,
    productid       NUMBER,
    quantityinstock NUMBER,
    lastupdated     DATE
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.inventory
    ADD CONSTRAINT inventory_pk
        PRIMARY KEY ( inventoryid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

CREATE TABLE c##hr.order_items (
    orderitemid NUMBER NOT NULL,
    orderid     NUMBER,
    productid   NUMBER,
    quantity    NUMBER,
    subtotal    NUMBER(10, 2)
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.order_items
    ADD CONSTRAINT order_items_pk
        PRIMARY KEY ( orderitemid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

CREATE TABLE c##hr.orders (
    orderid     NUMBER NOT NULL,
    customerid  NUMBER,
    orderdate   DATE,
    totalamount NUMBER(10, 2)
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.orders
    ADD CONSTRAINT orders_pk
        PRIMARY KEY ( orderid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

CREATE TABLE c##hr.products (
    productid   NUMBER NOT NULL,
    productname VARCHAR2(100 BYTE) NOT NULL,
    categoryid  NUMBER,
    supplierid  NUMBER,
    price       NUMBER(10, 2),
    description VARCHAR2(255 BYTE)
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.products
    ADD CONSTRAINT products_pk
        PRIMARY KEY ( productid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

CREATE TABLE c##hr.suppliers (
    supplierid   NUMBER NOT NULL,
    suppliername VARCHAR2(100 BYTE),
    contactemail VARCHAR2(100 BYTE)
)
PCTFREE 10
PCTUSED 40
TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
NO INMEMORY;

ALTER TABLE c##hr.suppliers
    ADD CONSTRAINT suppliers_pk
        PRIMARY KEY ( supplierid )
            USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users
LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    );

ALTER TABLE c##hr.orders
    ADD
        FOREIGN KEY ( customerid )
            REFERENCES c##hr.customers ( customerid )
            NOT DEFERRABLE;

ALTER TABLE c##hr.products
    ADD
        FOREIGN KEY ( categoryid )
            REFERENCES c##hr.categories ( categoryid )
            NOT DEFERRABLE;

ALTER TABLE c##hr.products
    ADD
        FOREIGN KEY ( supplierid )
            REFERENCES c##hr.suppliers ( supplierid )
            NOT DEFERRABLE;

ALTER TABLE c##hr.order_items
    ADD
        FOREIGN KEY ( orderid )
            REFERENCES c##hr.orders ( orderid )
            NOT DEFERRABLE;

ALTER TABLE c##hr.order_items
    ADD
        FOREIGN KEY ( productid )
            REFERENCES c##hr.products ( productid )
            NOT DEFERRABLE;

ALTER TABLE c##hr.inventory
    ADD
        FOREIGN KEY ( productid )
            REFERENCES c##hr.products ( productid )
            NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
